name: quiz_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  flutter_riverpod: ^2.4.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  riverpod: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: any
  nock: ^1.2.3
  

flutter:
  uses-material-design: true
